services:
  counting-request-client:
    build:
      context: .
      dockerfile: counting_request_client/Dockerfile.release
  counting-response-server:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: counting_response_server/Dockerfile.release
