FROM ubuntu:22.04

RUN sed -i 's|http://archive.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list && \
  sed -i 's|http://security.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list

RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  curl \
  gdb \
  git \
  htop \
  iftop \
  iperf \
  python3 \
  python3-pip \
  wget \
  xclip \
  zip \
  unzip \
  vim \
  net-tools && \
  rm -rf /var/lib/apt/lists/*

COPY ./scripts/install_grpc_cplusplus.sh /usr/local/bin/scripts/install_grpc_cplusplus.sh
RUN bash -c "source /usr/local/bin/scripts/install_grpc_cplusplus.sh && install_grpc_cplusplus && rm -rf /usr/local/bin/scripts/install_grpc_cplusplus.sh"
RUN apt-get update && apt-get install -y protobuf-compiler protobuf-compiler-grpc

ARG USERNAME=client_user
RUN useradd -ms /bin/bash $USERNAME

WORKDIR /home/$USERNAME

COPY --chown=$USERNAME:$USERNAME ./ ./grpc_test
USER $USERNAME

WORKDIR /home/$USERNAME/grpc_test/counting_request_client
RUN bash -c "source build.sh && build_counting_request_client"

# Change working directory to the build output and set the default command
WORKDIR /home/$USERNAME/counting_request_client/build
CMD ["./counting_request_client"]
