FROM ubuntu:22.04

RUN sed -i 's|http://archive.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list && \
  sed -i 's|http://security.ubuntu.com|http://mirror.kakao.com|g' /etc/apt/sources.list

RUN apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  build-essential \
  cmake \
  curl \
  gdb \
  git \
  htop \
  iftop \
  iperf \
  python3 \
  python3-pip \
  wget \
  xclip \
  zip \
  unzip \
  vim \
  net-tools && \
  rm -rf /var/lib/apt/lists/*

COPY ./scripts/install_grpc_python.sh /usr/local/bin/scripts/install_grpc_python.sh
RUN bash -c "source /usr/local/bin/scripts/install_grpc_python.sh && install_grpc_python && rm -rf /usr/local/bin/scripts/install_grpc_python.sh"

ARG USERNAME=vscode
RUN useradd -ms /bin/bash $USERNAME

WORKDIR /home/$USERNAME
COPY --chown=$USERNAME:$USERNAME ./ ./grpc_test
USER $USERNAME

WORKDIR /home/$USERNAME/grpc_test/counting_response_server
RUN bash -c "source build.sh && build_counting_response_server"

CMD ["python3", "main.py"]
